modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/Alfakynz/No-More-Popups/issues"
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL="https://github.com/Alfakynz/No-More-Popups"
logoFile = "assets/${mod_id}/icon.png"
authors = "${mod_author}"
description = '''${description}'''
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_loader_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "cloth_config"
mandatory = false
versionRange = "${clothconfig_version}"
ordering = "NONE"
side = "BOTH"
