modLoader = "javafml" #mandatory
loaderVersion = "${forge_loader_version_range}" #mandatory
license = "${license}"
issueTrackerURL="https://github.com/Alfakynz/No-More-Popups/issues" #optional
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL="https://alfakynz.github.io/No-More-Popups" #optional
logoFile = "assets/${mod_id}/icon.png" #optional
authors = "${mod_author}" #optional
description = '''${description}''' #mandatory
[[dependencies.${mod_id}]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_loader_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
